### ISSUE TITLE
How to use cayman-theme as  a jekyll layout

### ISSUE THREAD

**Issue by TommyJerryMairo** [jasonlong/cayman-theme#15]
Hello
I admire your cayman-theme, and want to use it to modify my blog.
However, I am new to web development and do not know how to use it as as jekyll layout.
So, can you help me and present a simple tutorial about how to use it in jekyll?

**Comment by jasonlong** [comment]
I'm wondering if @zbeekman had any luck with this as he brought this up in #10.

Another potential resource would be to look at https://github.com/pietromenna/jekyll-architect-theme since @pietromenna ported one of my other themes to Jekyll.

**Comment by zbeekman** [comment]
@jasonlong I ended up going with a jekyll theme based on the [Bootstrap Agency theme](https://github.com/y7kim/agency-jekyll-theme), with heavy modifications. My website is here: https://izaakbeekman.com and the repo is here: https://github.com/zbeekman/zbeekman.github.io

I'm still trying to figure out a good way to use a font, without adversely impacting the google page speep load benchmarks. Hopefully I'll find a way to inline the fonts/css needed for the above the fold content and load the rest of the font asynchronously with java script...

@TommyJerryMairo please let me know if you have any luck porting to jekyll

**Comment by pietromenna** [comment]
Hey! I also liked the idea to port Cayman to a Jekyll theme! I will try to do it by next monday! I will keep you posted!

**Comment by jasonlong** [comment]
Nice, thanks @pietromenna!

**Comment by pietromenna** [comment]
Hey! I have an initial version which can be found @ https://github.com/pietromenna/jekyll-cayman-theme . 

It should be working, but please, feel free to add any issues you find or to submit PR.

**Comment by TommyJerryMairo** [comment]
Tks all above, I think my problem has been solved.

**Comment by jasonlong** [comment]
Awesome! I added a link to the Jekyll port in the README.
