### ISSUE TITLE
Implement Dark Mode CSS

### ISSUE THREAD

**Issue by ghost** [jasonlong/cayman-theme#24]
https://webkit.org/blog/8840/dark-mode-support-in-webkit/

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

It's just two line of CSS.

**Comment by lapolinar** [comment]
@jasonlong

**Comment by benthecoder** [comment]
Are there any updates to dark mode?

**Comment by jasonlong** [comment]
The official repo for the Cayman Pages theme is now at https://github.com/pages-themes/cayman. I'm no longer a GitHub employee so I don't have any say in what features they'll be supporting.
