### ISSUE TITLE
Link with a code block should have blue color?

### ISSUE THREAD

**Issue by arkivanov** [jasonlong/cayman-theme#26]
I really like this theme but this issue prevents me from using it.

If I put a code block inside a link text then the link text is not highlighted:
```
[`Text`](https://www.google.com)
```

Actual result: the link color is gray
Expected result: the link color is blue

E.g. standard GitHub readme displays this case as expected.

**Comment by jasonlong** [comment]
Thanks @arkivanov. I've got this fixed in #27 and will get it updated on github.com for those using the theme.

**Comment by jasonlong** [comment]
FYI: https://github.com/pages-themes/cayman/pull/86
