### ISSUE TITLE
Cool idea: Geometric patterns as header background

### ISSUE THREAD

**Issue by Jamesking56** [jasonlong/cayman-theme#9]
Hello,

Noticed your other project Geometric patterns and I thought it would be cool if you could use one of those as a header background on this theme...

Any ideas if this is possible?

**Comment by jasonlong** [comment]
That's definitely possible. You'd just need to manually update the styles for the `.page-header` section. My geo_pattern library uses Ruby and is meant to be run on the server, but using the JS port by @btmills would be a good option. https://github.com/btmills/geopattern
